<body>
    <main class="">
        
        <div class ="mains bg-orange-300 ">
            <h1 class="p-5 text-white text-center text-3xl font-bold py-2 drop-shadow-xl">Crear Tasca</h1>
            <form action="" class="p-5">
                <label for="nombre">Nom: </label> <br>
                <input type="text" id="nombre" name="nom" class="rounded-md w-full"><br><br>
                <label for="data">Data: </label> <br>
                <input type="date" id="data" name="data_inici" class="rounded-md w-full"><br><br>
                <label>Estat: </label> <br>
                <INPUT TYPE="checkbox" NAME="estat" VALUE="pendent" class="rounded-full">Pendent
                <INPUT TYPE="checkbox" NAME="estat" VALUE="execusio" class="rounded-full">En execusió
                <INPUT TYPE="checkbox" NAME="estat" VALUE="acabada" class="rounded-full">Finalitzada<br><br>
                <input type="submit" value="Guardar" class="boton w-full  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            </form>
        </div>
    </main>
</body>