<body>
    <main>
        
        <div class ="h-3/4 mains bg-orange-300 sm:mx-auto sm:mx-auto my-32 ">
            <h1 class="p-5 text-white text-center text-3xl font-bold py-2 drop-shadow-xl">Vista de Tasca</h1>
            
            <h5 class="p-2 text-grey text-center text-1xl font-bold underline">Nom de la tasca:</h5>
            <p class="text-center"> <?php echo $_POST['tasca'];?></p><br>
            <h5 class="p-2 text-grey text-center text-1xl font-bold underline">Nom del creador:</h5>
            <p class="text-center"> <?php echo $_POST['nom'];?></p><br>
            <h5 class="p-2 text-grey text-center text-1xl font-bold underline">Data i hora d'inici:</h5>
            <p class="text-center"> <?php echo $_POST['inici'];?></p><br>
            <h5 class="p-2 text-grey text-center text-1xl font-bold underline">Data i hora de finalització:</h5>
            <p class="text-center"> <?php echo $_POST['final'];?></p><br>
            <h5 class="p-2 text-grey text-center text-1xl font-bold underline">Estat de la tasca:</h5>
            <p class="text-center"> <?php echo $_POST['estat'];?></p><br>
                     <!-- <a href="index" class="boton w-full  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">Tornar a tasques</a> -->
                     <div class="flex justify-center">
                <a href="index">
                    <button class="boton w-52  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Tornar a tasques</button>
                </a>
                
            </div>
        
        </div>
        

    </main>
</body>