<body class=" ">
    <main class="principal">

        <!-- <div class="cont_img relative">
            <img src="images/notebook.png" alt="cuaderno" width="100%">

        </div> -->
           
        <div class=" flex justify-center align-center flex-col mx-10">

            <button class="boton w-52  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
                <a href="http://localhost:3000/web/nova">Nova tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/mod">Modificar tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/eliminar">Eliminar tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/mostrar">Mostrar tasca</a>
            </button>

        </div>
    </main>
</body>
