<body class=" ">
    <main>
        <img src="https://img.freepik.com/foto-gratis/disposicion-elementos-escritorio-sobre-fondo-amarillo_23-2148513310.jpg?w=2000" alt="cuaderno" width="500" class="relative">
           
        <div class="absolute flex justify-around flex-col">

            <button class="boton w-52  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
                <a href="http://localhost:3000/web/nova">Nova tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/mod">Modificar tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/eliminar">Eliminar tasca</a>
            </button>
            
            <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            <a href="http://localhost:3000/web/mostrar">Mostrar tasca</a>
            </button>

        </div>
    </main>
</body>
