<body>
    <main>
        <div class="sm:container sm:mx-auto my-32 ">
            
            <div class="flex justify-center">
                <a href="nova">
                    <button class="boton w-52  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Nova tasca</button>
                </a>
                <a href="mostrar">
                    <button class="boton w-52 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">Buscar tasca</button>
                </a>
            </div>
           
            <div class="flex flex-col mt-4">
                <div class=" overflow-auto sm:-mx-4 sm:px-4 lg:-mx-4 lg:px-4">
                    <div class=" min-w-full overflow-hidden align-center rounded-lg inline-block">
                        <table class="min-w-full text-left leading-5 text-slate-50 border-collapse border border-slate-40">
                            <thead class="font bold bg-orange-500 text-center">
                                <tr class="border-b border-gray-200">
                                    <th class="p-4 text-sm">NOM TASCA</th>
                                    <th class="p-4 text-sm">NOM DEL CREADOR</th>
                                    <th class="p-4 text-sm">ESTAT</th>
                                    <th class="p-4 text-sm">HORA D'INICI</th>
                                    <th class="p-4 text-sm">HORA FINALITZACIO</th>
                                    <th class="p-4 text-sm"></th>
                                </tr>
                            </thead>
                            <!-- Contingut de tasques -->
                            <tbody class="bgspecial  border-gray-200 text-gray-900 text-center">
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/mod"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>
                                <tr class="border-b border-gray-200">
                                    <td class="p-4">Fumar petas</td>
                                    <td class="p-4">Eddie</td>
                                    <td class="p-4">Pendent</td>
                                    <td class="p-4">20/02/22</td>
                                    <td class="p-4">21/02/22</td>
                                    <td class="text-sm font-medium">
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                                        <a href="/web/nova"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button></a>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
