<div class ="rounded-md mt-32 bg-orange-300 max-w-screen-sm mx-auto">
            <h1 class="p-5 text-white text-center text-3xl font-bold py-2 drop-shadow-xl">Buscar Tasca</h1>
            <p class="p-5 text-white text-center text-2xl font-bold py-2 drop-shadow-xl">Introdueix el nom de la tasca a buscar.</p>

            <form action="" method="POST" class="p-5">
                <label for="nom_tasca">Nom de tasca: </label> <br>
                <input type="text" id="nom_tasca" name="nom_tasca" class="rounded-md w-full outline-orange-500 mb-2"><br>
                <input type="submit" value="Buscar" class="boton w-full  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            </form>
</div>