<div class ="rounded-md mt-32 bg-orange-300 max-w-screen-sm mx-auto">
            <h1 class="p-5 text-white text-center text-3xl font-bold py-2 drop-shadow-xl">Buscar Tasca</h1>
            <p class="p-5 text-white text-center text-2xl font-bold py-2 drop-shadow-xl">Introdueix el nom de la tasca a buscar.</p>

            <form action="buscador" method="POST" class="p-5">
                <label for="nom_tasca">Nom de tasca: </label> <br>
                <input type="text" id="nom_tasca" name="tasca" class="rounded-md w-full outline-orange-500 mb-2"><br>
                <input type="submit" value="Buscar" class="boton w-full  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full">
            </form>
</div>

    <?php if (isset($tasca)) {?>
        <div><?php echo $tasca ?></div>
    <?php } ?>
<div class="flex flex-col mt-4 sm:container sm:mx-auto my-32 ">
    <div class=" overflow-auto sm:-mx-4 sm:px-4 lg:-mx-4 lg:px-4">
        <div class=" min-w-full overflow-hidden align-center rounded-lg inline-block">
            <table class="min-w-full text-left leading-5 text-slate-50 border-collapse border border-slate-40">
                <thead class="font bold bg-orange-500 text-center">
                    <tr class="border-b border-gray-200">
                        <th class="p-4 text-sm">NOM TASCA</th>
                        <th class="p-4 text-sm">NOM DEL CREADOR</th>
                        <th class="p-4 text-sm">ESTAT</th>
                        <th class="p-4 text-sm">HORA D'INICI</th>
                        <th class="p-4 text-sm">HORA FINALITZACIO</th>
                        <th class="p-4 text-sm"></th>
                    </tr>
                </thead>
                <tbody class="bgspecial  border-gray-200 text-gray-900 text-center">
                <?php require_once '../app/models/ddbb.php';?>
                    <tr class="border-b border-gray-200">
                        <td class="p-4"></td>
                        <td class="p-4"></td>
                        <td class="p-4"></td>
                        <td class="p-4"></td>
                        <td class="p-4"></td>
                        <td class="text-sm font-medium">
                            <a href="/web/mod"><button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full mr-5">Editar</button></a>
                            <form action="eliminar" method="post" style="display: inline-block" class="mr-1">
                            <input type="hidden" name='id' value="<?php echo $key['id']; ?>">
                                <button class="boton w-20  bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded-full ">Eliminar</button>
                            </from>
                        </td>
                    </tr>
                </tbody>
            </table>    
        </div>
    </div>
</div>
