<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.tailwindcss.com"></script>
	<link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" >

	
	
</head>
<body>
	<?php include 'header.php'; ?>
	<!-- <?php echo 'estoy antes de cargar mi vista <br>'; ?> -->
	<?php echo $this->content(); ?>
	<!-- <?php echo '<br> estoy despues de cargar mi vista <br>'; ?> -->
	<?php include 'footer.php'; ?>
</body>
</html>